### ISSUE TITLE
Serial Comms

### ISSUE THREAD

**Issue by pawaller** [lennart-benschop/agon-forth#3]
Hi Lennart,
I am struggling to use the Nanno.bin you recommend to edit, the colours seem all screwed up and the screen is unreadable, not sure it is because I am still on firmware 1.02 but waiting for official release before upgrading to 1.03.

Would it be possible to connect to forth using serial comms?
I am used to editing in visual studio and then squirting the source code across over a serial connection.
I did try hooking up PC0 & PC1 on the GPIO but could not get it to work.

I think USB-C is power only so the only way is via GPIO??

Thanks once again for all your assistance
Phil

**Comment by lennart-benschop** [comment]
Hi Phil,

If you are still on Firmware 1.02, please use the last version of nano 
that was checked into git in January 2023. I'm currently tracking the 
1.03 Firmware and quite a bit has changed since then for example the VDU 
codes to set colours and the way key presses are passed to the eZ80.

I think the coming version of the firmware will have a way to send key 
presses over the serial port as well (instead of the PS/2 keyboard).

--

Lennart

**Comment by pawaller** [comment]
That version of nano works fine, thanks

**Comment by pawaller** [comment]
That version of nano works fine, thanks
